# Copyright 2026 allurx
# SPDX-License-Identifier: Apache-2.0

name: CI

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

permissions:
    contents: read

concurrency:
    group: ci-${{ github.ref }}
    cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
    site:
        uses: allurx/web-foundation/.github/workflows/static-site.yml@e32472d639aa24562baa026a233a8cfac2d27d7c # v1.0.0
        with:
            asset-directory: dist/
            production-url: https://allurx.io
